### ISSUE TITLE
(compat issue with MCA + Iris Shaders) Severe framerate drop when performing parkour animation

### ISSUE THREAD

**Issue by ChromaPIE** [BeeeBea/FastMove#15]
As the title said, doing parkour moves introduced by this mod has a huge impact on the framerate. I tend to play with V-sync on and get solid 60 most of the time, when and only when doing parkour the framerate drops to around 30.

I'm on Fabric 1.20.1, mod version 1.0.4, Sodium, Indium and Iris shaderpack (Complementary Reimagined) on. Let me know if you need more info like the full mod list, log, etc..

**Comment by BeeeBea** [comment]
Hey! Thanks for letting me know about this performance issue <3. 

I was unable to replicate the problem using the most recent two versions of Sodium/Indium/Iris/Complementary. I also couldn't find any meaningful impact of FastMove when profiling using [spark](https://modrinth.com/mod/spark).

If possible, could you check to see if you still encounter this issue when no other mods are loaded. If not, the full mod list and a log would be appreciated.

Thanks again!

**Comment by ChromaPIE** [comment]
Thanks for replying! I'm just about to report a crash to another repo so imma just paste that fresh crash report here bc the mod list is inside, start from line 127.

I'm kinda sure it's an inter-mod problem. The performance issue I believe wasn't here, or at least wasn't that intense to annoy me before Minecraft Comes Alive was included in the instance. It's prolly caused by its optional modified player model, so if you don't find any other mods in the pack suspicious, make sure to choose the appearance from MCA and see how it goes.

**Comment by BeeeBea** [comment]
Looks like its an issue with the combination of MCA, Iris, and bendy-lib  :/ 

![image](https://github.com/BeeeBea/FastMove/assets/33187487/27f5ef55-de44-4803-af01-048ac0355477)

bendy-lib is not essential for this mod to work, but the animations do look a little bit goofy without it. I'll try making a build later without including it and I'll see what happens :3

**Comment by BeeeBea** [comment]
Bendy-Lib is no longer required / included with the mod. I'd still recommend using it but it is not essential now :)
