### ISSUE TITLE
Compatibility issue with Immersive Aircraft

### ISSUE THREAD

**Issue by ChromaPIE** [BeeeBea/FastMove#16]
Immersive Aircraft binds the key descending aircrafts to Shift by default, which doesnt have to be changes unless you rebind the sneak key too, bc it just feels right to correspond to each other.

So the problem is obvious. When you are on an aircraft you are mid-air, so holding the key to descent the plane also causes the player to roll and end up crawling up there.

Sure the mod could use a compat patch that disables the parkour tricks for players flying an Immersive Aircraft (or maybe a better way, I'm no pro), bc it's dangerous to roll on some rickety flying planks.

**Comment by BeeeBea** [comment]
Thanks for another bug report <3

Hopefully this issue should be avoided with the changes from [this issue](https://github.com/BeeeBea/FastMove/issues/14). If Immersive Aircraft sets the player's vehicle in a similar way to vanilla, fast move inputs should be prevented completely. If not, the default keybinds can be changed instead.

These changes are not yet in a release version, but will be included in the next build :]
