### ISSUE TITLE
game crashes when using with tweakeroo free cam

### ISSUE THREAD

**Issue by Saiko125** [BeeeBea/FastMove#3]
[crash-2023-09-01_14.53.41-client.txt](https://github.com/BeeeBea/FastMove/files/12500078/crash-2023-09-01_14.53.41-client.txt)

when I press free cam keybind it crashes the game

**Comment by BeeeBea** [comment]
@Saiko125 Should be fixed with [version 1.0.3](https://modrinth.com/mod/fastmove/version/1.0.3)
