### ISSUE TITLE
[Feedback] Elytra + Roll is so OP

### ISSUE THREAD

**Issue by Zorklis** [BeeeBea/FastMove#5]
It's so Overpowered, I can start gliding and then look up and then do a roll and it launches me into the air, no rockets required anymore. I love this.
The slide is cool.

**Comment by Saiko125** [comment]
when swimming and doing dive roll you gain insane speeds

**Comment by Zorklis** [comment]
Nah, roll + elytra is crazier and more insane. It's very fun too

**Comment by BeeeBea** [comment]
The issue with rolling while flying / swimming should be fixed with [version 1.0.4](https://modrinth.com/mod/fastmove/version/1.0.4)!

There is now an option in the config that enables it again (if you wanna have fun)  ;3

**Comment by Zorklis** [comment]
It sure does save me a ton of fireworks :)
Also nice that you fixed the hover when prone, was one of my nitpicks tbh

**Comment by Zorklis** [comment]
Seems like this has been completely removed, due to other updates to the roll it no longer works even with elytra roll option turned on. It was nice while it lasted
