### ISSUE TITLE
crash with 0 tick duration for wall running

### ISSUE THREAD

**Issue by Saiko125** [BeeeBea/FastMove#6]
after setting wall running duration to 0 and attempting to wall run game crashes/freezes

**Comment by BeeeBea** [comment]
Thanks for finding this! This issue should now be prevented in the config with [version 1.0.4](https://modrinth.com/mod/fastmove/version/1.0.4)

Each distinct movement mechanic now has a toggle in the config too (just in case that's why it was set to 0 ticks)
