### ISSUE TITLE
Roll occurs even while flying or swimming

### ISSUE THREAD

**Issue by GalatynF** [BeeeBea/FastMove#7]
As the title says, pressing sneak always performs the roll as long as the player is not touching the ground, which is annoying when wanting to get to the bottom of a pool for example, and is extremely OP when flying as it essentially gives free boosting.

The check on line 226 of PlayerEntityMixin should probably be more restrictive, checking if : 
* The player doesn't have an elytra equipped or is not flying (I don't remember if there is such a function)
* The player is not touching water

**Comment by GalatynF** [comment]
And yes, someone already raised the issue with elytras but I wanted to address the source cause and add the water issue to that

**Comment by BeeeBea** [comment]
Thank you for the detailed issue! 

This should now be fixed with [version 1.0.4](https://modrinth.com/mod/fastmove/version/1.0.4) :)
